-- ============================================================================
-- Migration: tiktok_schema.sql
-- Purpose: Database schema for TikTok automation module
-- Author: Agent 11 - WaitingTheLongest Build System
-- Created: 2024-01-28
--
-- DEPENDENCIES: 001_extensions.sql (uuid-ossp), 004_dogs.sql (dogs table)
--
-- TABLES CREATED:
-- - tiktok_posts: Main post storage with scheduling and analytics
-- - tiktok_templates: Custom template storage (supplements code defaults)
-- - tiktok_analytics_history: Historical analytics tracking
--
-- ROLLBACK: DROP TABLE statements at end of file (commented)
-- ============================================================================

-- ============================================================================
-- TIKTOK_POSTS TABLE
-- Purpose: Store TikTok posts with scheduling, status, and analytics
-- ============================================================================
CREATE TABLE IF NOT EXISTS tiktok_posts (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Relationships
    dog_id UUID NOT NULL REFERENCES dogs(id) ON DELETE CASCADE,
    shelter_id UUID REFERENCES shelters(id) ON DELETE SET NULL,

    -- Template
    template_type VARCHAR(50),              -- urgent_countdown, longest_waiting, etc.

    -- Content
    caption TEXT NOT NULL,                  -- Post caption (max 2200 chars for TikTok)
    hashtags TEXT[] DEFAULT '{}',           -- Array of hashtags
    music_id VARCHAR(100),                  -- TikTok sound ID
    music_name VARCHAR(255),                -- Sound display name

    -- Media
    content_type VARCHAR(50) DEFAULT 'video', -- video, photo_slideshow, single_photo
    video_url TEXT,                         -- Video URL for upload
    photo_urls TEXT[] DEFAULT '{}',         -- Photo URLs for slideshow
    thumbnail_url TEXT,                     -- Thumbnail image URL

    -- Overlay/Styling
    overlay_text TEXT,                      -- Text overlay content
    overlay_style VARCHAR(50),              -- Overlay style preset
    include_countdown BOOLEAN DEFAULT FALSE, -- Show urgency countdown
    include_wait_time BOOLEAN DEFAULT FALSE, -- Show wait time display

    -- Scheduling
    scheduled_at TIMESTAMP WITH TIME ZONE,  -- When to post
    posted_at TIMESTAMP WITH TIME ZONE,     -- When actually posted
    auto_generated BOOLEAN DEFAULT FALSE,   -- Generated by worker

    -- Status
    status VARCHAR(30) DEFAULT 'draft',     -- draft, scheduled, pending_approval, posting, published, failed, deleted, expired
    tiktok_post_id VARCHAR(100),            -- TikTok's ID after posting
    tiktok_url TEXT,                        -- Direct URL to posted TikTok
    error_message TEXT,                     -- Error message if failed
    retry_count INTEGER DEFAULT 0,          -- Number of posting retries

    -- Analytics (JSONB for flexibility)
    analytics JSONB DEFAULT '{
        "views": 0,
        "likes": 0,
        "shares": 0,
        "comments": 0,
        "saves": 0,
        "engagement_rate": 0,
        "reach": 0,
        "profile_visits": 0
    }'::jsonb,

    -- Metadata
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    approved_by UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Comments for documentation
COMMENT ON TABLE tiktok_posts IS 'TikTok posts for dog awareness campaigns';
COMMENT ON COLUMN tiktok_posts.dog_id IS 'Reference to the dog this post is about';
COMMENT ON COLUMN tiktok_posts.template_type IS 'Template used: urgent_countdown, longest_waiting, overlooked_angel, foster_plea, happy_update, educational';
COMMENT ON COLUMN tiktok_posts.status IS 'Post lifecycle status: draft, scheduled, pending_approval, posting, published, failed, deleted, expired';
COMMENT ON COLUMN tiktok_posts.analytics IS 'JSON object storing engagement metrics from TikTok API';
COMMENT ON COLUMN tiktok_posts.auto_generated IS 'True if post was auto-generated by the background worker';

-- ============================================================================
-- TIKTOK_TEMPLATES TABLE
-- Purpose: Store custom templates (supplements defaults defined in code)
-- ============================================================================
CREATE TABLE IF NOT EXISTS tiktok_templates (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Identity
    template_id VARCHAR(100) UNIQUE NOT NULL, -- Custom identifier (e.g., shelter_urgent_tx)
    name VARCHAR(255) NOT NULL,             -- Display name
    type VARCHAR(50) NOT NULL,              -- urgent_countdown, longest_waiting, etc.
    description TEXT,                       -- Template description

    -- Caption Template
    caption_template TEXT NOT NULL,         -- Caption with {placeholders}
    required_placeholders TEXT[] DEFAULT '{}', -- Placeholders that must be filled
    optional_placeholders TEXT[] DEFAULT '{}', -- Placeholders that are optional

    -- Hashtags
    default_hashtags TEXT[] DEFAULT '{}',   -- Always-included hashtags
    optional_hashtags TEXT[] DEFAULT '{}',  -- May-be-included hashtags
    max_hashtags INTEGER DEFAULT 10,        -- Maximum hashtags to use

    -- Styling
    overlay_style VARCHAR(50),              -- Overlay style preset
    suggested_music_id VARCHAR(100),        -- Suggested TikTok sound
    suggested_music_name VARCHAR(255),      -- Sound display name
    include_countdown BOOLEAN DEFAULT FALSE,
    include_wait_time BOOLEAN DEFAULT FALSE,
    text_overlay_template TEXT,             -- Overlay text template

    -- Timing
    optimal_post_hours INTEGER[] DEFAULT '{9,12,17,20}', -- Hours (0-23)
    auto_generate_enabled BOOLEAN DEFAULT FALSE,
    priority INTEGER DEFAULT 0,             -- Higher = more important

    -- Ownership
    shelter_id UUID REFERENCES shelters(id) ON DELETE CASCADE, -- NULL = global
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,

    -- State
    is_active BOOLEAN DEFAULT TRUE,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Comments
COMMENT ON TABLE tiktok_templates IS 'Custom TikTok post templates, supplements built-in defaults';
COMMENT ON COLUMN tiktok_templates.template_id IS 'Unique identifier for the template (used in API)';
COMMENT ON COLUMN tiktok_templates.shelter_id IS 'NULL for global templates, shelter UUID for shelter-specific';
COMMENT ON COLUMN tiktok_templates.caption_template IS 'Caption with placeholders like {dog_name}, {wait_time}, {shelter_name}';

-- ============================================================================
-- TIKTOK_ANALYTICS_HISTORY TABLE
-- Purpose: Store historical analytics for trend analysis
-- ============================================================================
CREATE TABLE IF NOT EXISTS tiktok_analytics_history (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Reference
    post_id UUID NOT NULL REFERENCES tiktok_posts(id) ON DELETE CASCADE,

    -- Analytics snapshot
    views BIGINT DEFAULT 0,
    likes BIGINT DEFAULT 0,
    shares BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    saves BIGINT DEFAULT 0,
    engagement_rate DECIMAL(5,2) DEFAULT 0,
    reach BIGINT DEFAULT 0,
    profile_visits BIGINT DEFAULT 0,

    -- Timestamp
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Comments
COMMENT ON TABLE tiktok_analytics_history IS 'Historical analytics snapshots for TikTok posts';
COMMENT ON COLUMN tiktok_analytics_history.post_id IS 'Reference to the TikTok post';
COMMENT ON COLUMN tiktok_analytics_history.recorded_at IS 'When these analytics were recorded';

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Posts indexes
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_dog_id ON tiktok_posts(dog_id);
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_shelter_id ON tiktok_posts(shelter_id);
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_status ON tiktok_posts(status);
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_scheduled_at ON tiktok_posts(scheduled_at)
    WHERE status = 'scheduled';
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_template_type ON tiktok_posts(template_type);
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_created_at ON tiktok_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_tiktok_post_id ON tiktok_posts(tiktok_post_id)
    WHERE tiktok_post_id IS NOT NULL;

-- Analytics JSON index for sorting by metrics
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_analytics_views
    ON tiktok_posts(((analytics->>'views')::bigint) DESC);
CREATE INDEX IF NOT EXISTS idx_tiktok_posts_analytics_engagement
    ON tiktok_posts(((analytics->>'engagement_rate')::float) DESC);

-- Templates indexes
CREATE INDEX IF NOT EXISTS idx_tiktok_templates_type ON tiktok_templates(type);
CREATE INDEX IF NOT EXISTS idx_tiktok_templates_shelter_id ON tiktok_templates(shelter_id);
CREATE INDEX IF NOT EXISTS idx_tiktok_templates_active ON tiktok_templates(is_active)
    WHERE is_active = TRUE;

-- Analytics history indexes
CREATE INDEX IF NOT EXISTS idx_tiktok_analytics_history_post_id ON tiktok_analytics_history(post_id);
CREATE INDEX IF NOT EXISTS idx_tiktok_analytics_history_recorded_at ON tiktok_analytics_history(recorded_at DESC);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update timestamp trigger for posts
CREATE OR REPLACE FUNCTION update_tiktok_posts_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tiktok_posts_updated_at
    BEFORE UPDATE ON tiktok_posts
    FOR EACH ROW
    EXECUTE FUNCTION update_tiktok_posts_timestamp();

-- Update timestamp trigger for templates
CREATE TRIGGER tiktok_templates_updated_at
    BEFORE UPDATE ON tiktok_templates
    FOR EACH ROW
    EXECUTE FUNCTION update_tiktok_posts_timestamp();

-- ============================================================================
-- VIEWS
-- ============================================================================

-- View: Posts with calculated metrics
CREATE OR REPLACE VIEW tiktok_posts_with_metrics AS
SELECT
    tp.*,
    d.name as dog_name,
    d.breed_primary as dog_breed,
    d.urgency_level as dog_urgency,
    (tp.analytics->>'views')::bigint as view_count,
    (tp.analytics->>'likes')::bigint as like_count,
    (tp.analytics->>'shares')::bigint as share_count,
    (tp.analytics->>'comments')::bigint as comment_count,
    (tp.analytics->>'engagement_rate')::float as engagement_rate,
    CASE
        WHEN tp.scheduled_at IS NOT NULL THEN tp.scheduled_at - NOW()
        ELSE NULL
    END as time_until_scheduled
FROM tiktok_posts tp
LEFT JOIN dogs d ON tp.dog_id = d.id;

COMMENT ON VIEW tiktok_posts_with_metrics IS 'TikTok posts with extracted analytics metrics and dog info';

-- View: Scheduled posts due for posting
CREATE OR REPLACE VIEW tiktok_posts_due AS
SELECT *
FROM tiktok_posts
WHERE status = 'scheduled'
  AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC;

COMMENT ON VIEW tiktok_posts_due IS 'Scheduled posts that are past their scheduled time';

-- View: Analytics summary by template type
CREATE OR REPLACE VIEW tiktok_template_performance AS
SELECT
    template_type,
    COUNT(*) as total_posts,
    COUNT(*) FILTER (WHERE status = 'published') as published_posts,
    SUM((analytics->>'views')::bigint) as total_views,
    SUM((analytics->>'likes')::bigint) as total_likes,
    SUM((analytics->>'shares')::bigint) as total_shares,
    AVG((analytics->>'engagement_rate')::float) as avg_engagement_rate
FROM tiktok_posts
WHERE status = 'published'
GROUP BY template_type
ORDER BY total_views DESC;

COMMENT ON VIEW tiktok_template_performance IS 'Performance metrics grouped by template type';

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function: Record analytics snapshot
CREATE OR REPLACE FUNCTION record_tiktok_analytics_snapshot(p_post_id UUID)
RETURNS VOID AS $$
DECLARE
    v_analytics JSONB;
BEGIN
    SELECT analytics INTO v_analytics
    FROM tiktok_posts
    WHERE id = p_post_id;

    IF v_analytics IS NOT NULL THEN
        INSERT INTO tiktok_analytics_history (
            post_id, views, likes, shares, comments, saves,
            engagement_rate, reach, profile_visits
        ) VALUES (
            p_post_id,
            (v_analytics->>'views')::bigint,
            (v_analytics->>'likes')::bigint,
            (v_analytics->>'shares')::bigint,
            (v_analytics->>'comments')::bigint,
            (v_analytics->>'saves')::bigint,
            (v_analytics->>'engagement_rate')::decimal,
            (v_analytics->>'reach')::bigint,
            (v_analytics->>'profile_visits')::bigint
        );
    END IF;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION record_tiktok_analytics_snapshot IS 'Records current analytics as a historical snapshot';

-- Function: Get posts needing analytics update
CREATE OR REPLACE FUNCTION get_tiktok_posts_for_analytics_update(p_limit INTEGER DEFAULT 50)
RETURNS SETOF tiktok_posts AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM tiktok_posts
    WHERE status = 'published'
      AND tiktok_post_id IS NOT NULL
      AND (
          (analytics->>'last_updated') IS NULL
          OR (analytics->>'last_updated')::timestamp < NOW() - INTERVAL '1 hour'
      )
    ORDER BY
        -- Prioritize posts that haven't been updated recently
        (analytics->>'last_updated')::timestamp NULLS FIRST,
        -- Then by engagement (more popular posts get updated more often)
        (analytics->>'views')::bigint DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_tiktok_posts_for_analytics_update IS 'Returns posts that need analytics refresh from TikTok API';

-- Function: Cleanup old analytics history
CREATE OR REPLACE FUNCTION cleanup_tiktok_analytics_history(p_retention_days INTEGER DEFAULT 90)
RETURNS INTEGER AS $$
DECLARE
    v_deleted INTEGER;
BEGIN
    DELETE FROM tiktok_analytics_history
    WHERE recorded_at < NOW() - (p_retention_days || ' days')::interval;

    GET DIAGNOSTICS v_deleted = ROW_COUNT;
    RETURN v_deleted;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_tiktok_analytics_history IS 'Removes analytics history older than specified days (default 90)';

-- Function: Mark expired scheduled posts
CREATE OR REPLACE FUNCTION mark_expired_tiktok_posts()
RETURNS INTEGER AS $$
DECLARE
    v_updated INTEGER;
BEGIN
    UPDATE tiktok_posts
    SET status = 'expired', updated_at = NOW()
    WHERE status = 'scheduled'
      AND scheduled_at < NOW() - INTERVAL '1 hour';

    GET DIAGNOSTICS v_updated = ROW_COUNT;
    RETURN v_updated;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION mark_expired_tiktok_posts IS 'Marks scheduled posts as expired if they missed their posting window';

-- ============================================================================
-- SAMPLE/DEFAULT DATA
-- ============================================================================

-- Insert default global template (supplements code defaults)
-- This is optional - code has built-in defaults
-- Uncomment to add database-stored templates

/*
INSERT INTO tiktok_templates (
    template_id, name, type, description,
    caption_template, required_placeholders, optional_placeholders,
    default_hashtags, max_hashtags, include_countdown, priority
) VALUES (
    'db_urgent_countdown',
    'Urgent Countdown (DB)',
    'urgent_countdown',
    'Database-stored urgent countdown template',
    'URGENT: {dog_name} has only {urgency} left!

This sweet {breed} at {shelter_name} needs a hero NOW.

{dog_name} has been waiting {wait_time} for someone to notice them.

Can you be their second chance? Share to save a life!',
    ARRAY['dog_name', 'urgency', 'shelter_name'],
    ARRAY['breed', 'wait_time', 'location', 'age'],
    ARRAY['AdoptDontShop', 'UrgentDog', 'SaveALife', 'ShelterDog', 'RescueDog'],
    10,
    TRUE,
    100
) ON CONFLICT (template_id) DO NOTHING;
*/

-- ============================================================================
-- ROLLBACK SCRIPT (COMMENTED)
-- ============================================================================
/*
DROP VIEW IF EXISTS tiktok_template_performance;
DROP VIEW IF EXISTS tiktok_posts_due;
DROP VIEW IF EXISTS tiktok_posts_with_metrics;
DROP FUNCTION IF EXISTS mark_expired_tiktok_posts;
DROP FUNCTION IF EXISTS cleanup_tiktok_analytics_history;
DROP FUNCTION IF EXISTS get_tiktok_posts_for_analytics_update;
DROP FUNCTION IF EXISTS record_tiktok_analytics_snapshot;
DROP TRIGGER IF EXISTS tiktok_templates_updated_at ON tiktok_templates;
DROP TRIGGER IF EXISTS tiktok_posts_updated_at ON tiktok_posts;
DROP FUNCTION IF EXISTS update_tiktok_posts_timestamp;
DROP TABLE IF EXISTS tiktok_analytics_history;
DROP TABLE IF EXISTS tiktok_templates;
DROP TABLE IF EXISTS tiktok_posts;
*/
