/**
 * @file ContentGenerator.cc
 * @brief Implementation of MarkdownGenerator
 * @see ContentGenerator.h for documentation
 */

#include "content/blog/ContentGenerator.h"

// Standard library includes
#include <algorithm>
#include <cctype>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <regex>
#include <sstream>

// Project includes
#include "core/debug/ErrorCapture.h"

namespace wtl::content::blog {

// ============================================================================
// SINGLETON ACCESS
// ============================================================================

MarkdownGenerator& MarkdownGenerator::getInstance() {
    static MarkdownGenerator instance;
    return instance;
}

MarkdownGenerator::MarkdownGenerator() {
    // Default configuration
    config_ = GeneratorConfig();
}

MarkdownGenerator::~MarkdownGenerator() = default;

// ============================================================================
// CONFIGURATION
// ============================================================================

void MarkdownGenerator::setConfig(const GeneratorConfig& config) {
    std::lock_guard<std::mutex> lock(mutex_);
    config_ = config;
    template_cache_.clear();  // Clear cache when config changes
}

GeneratorConfig MarkdownGenerator::getConfig() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return config_;
}

// ============================================================================
// DOG FEATURE GENERATION
// ============================================================================

BlogPost MarkdownGenerator::generateDogFeature(
    const wtl::core::models::Dog& dog,
    const std::optional<wtl::core::models::Shelter>& shelter
) {
    BlogPost post;

    // Generate unique ID
    post.id = "";  // Will be generated by database

    // Generate title and slug
    post.title = generateDogFeatureTitle(dog);
    post.slug = BlogPost::generateSlug(post.title);

    // Generate content
    post.content = generateDogFeatureContent(dog, shelter);

    // Generate excerpt
    post.excerpt = generateExcerpt(post.content, config_.max_excerpt_length);

    // Classification
    if (dog.urgency_level == "critical" || dog.urgency_level == "high") {
        post.category = BlogCategory::URGENT;
    } else {
        post.category = BlogCategory::LONGEST_WAITING;
    }

    // Tags based on dog attributes
    post.tags = generateDogKeywords(dog);

    // Media
    if (!dog.photo_urls.empty()) {
        post.featured_image = dog.photo_urls[0];
        post.gallery_images = dog.photo_urls;
    }

    // Relationships
    post.dog_id = dog.id;
    if (shelter) {
        post.shelter_id = shelter->id;
    }

    // Status - default to draft
    post.status = PostStatus::DRAFT;

    // SEO
    auto seo = generateDogFeatureSeo(dog, shelter);
    post.meta_description = seo.description;
    post.og_title = seo.og_title;
    post.og_description = seo.og_description;
    post.og_image = seo.og_image;

    // Author
    post.author_name = config_.default_author;
    post.is_auto_generated = true;

    // Timestamps
    post.created_at = std::chrono::system_clock::now();
    post.updated_at = post.created_at;

    return post;
}

std::string MarkdownGenerator::generateDogFeatureContent(
    const wtl::core::models::Dog& dog,
    const std::optional<wtl::core::models::Shelter>& shelter
) {
    // Try to load template, fall back to inline template
    std::string template_content;
    try {
        template_content = loadTemplate("dog_feature.md.template");
    } catch (...) {
        // Inline fallback template
        template_content = R"(# Meet {{DOG_NAME}}: {{DOG_TAGLINE}}

{{FEATURED_IMAGE}}

## About {{DOG_NAME}}

{{DOG_DESCRIPTION}}

**{{DOG_NAME}} has been waiting {{WAIT_TIME}} for a forever home.**

## Quick Facts

{{DOG_ATTRIBUTES}}

## Personality & Temperament

{{PERSONALITY_SECTION}}

{{PHOTO_GALLERY}}

## Why {{DOG_NAME}} Needs You

{{WHY_ADOPT}}

{{CTA_SECTION}}

---

*Last updated: {{LAST_UPDATED}}*
)";
    }

    // Build placeholder map
    std::map<std::string, std::string> placeholders;

    // Basic info
    placeholders["DOG_NAME"] = dog.name;
    placeholders["DOG_ID"] = dog.id;

    // Generate tagline based on breed/age
    std::string tagline;
    if (dog.age_category == "puppy") {
        tagline = "An Adorable " + dog.breed_primary + " Puppy";
    } else if (dog.age_category == "senior") {
        tagline = "A Sweet Senior " + dog.breed_primary;
    } else {
        tagline = "A Wonderful " + dog.breed_primary;
    }
    placeholders["DOG_TAGLINE"] = tagline;

    // Featured image
    if (!dog.photo_urls.empty()) {
        placeholders["FEATURED_IMAGE"] = "![" + dog.name + "](" + dog.photo_urls[0] + ")";
    } else {
        placeholders["FEATURED_IMAGE"] = "";
    }

    // Description
    placeholders["DOG_DESCRIPTION"] = dog.description.empty() ?
        dog.name + " is looking for their perfect match!" : dog.description;

    // Wait time
    placeholders["WAIT_TIME"] = formatWaitTime(dog.intake_date);

    // Attributes
    placeholders["DOG_ATTRIBUTES"] = generateDogAttributes(dog);

    // Personality
    placeholders["PERSONALITY_SECTION"] = generatePersonalitySection(dog);

    // Photo gallery
    if (dog.photo_urls.size() > 1) {
        placeholders["PHOTO_GALLERY"] = "## More Photos\n\n" + generatePhotoGallery(dog.photo_urls);
    } else {
        placeholders["PHOTO_GALLERY"] = "";
    }

    // Why adopt section based on urgency
    if (dog.urgency_level == "critical") {
        placeholders["WHY_ADOPT"] = "**URGENT:** " + dog.name + " is in a critical situation and needs "
            "immediate help. Without rescue or adoption, this sweet pup may not have much time left. "
            "Can you open your heart and home?";
    } else if (dog.urgency_level == "high") {
        placeholders["WHY_ADOPT"] = dog.name + " is at high risk and desperately needs a "
            "loving home. Every day matters for dogs like " + dog.name + ".";
    } else {
        placeholders["WHY_ADOPT"] = dog.name + " has been patiently waiting and would make "
            "a wonderful addition to the right family. Don't let this amazing pup be overlooked!";
    }

    // CTA section
    placeholders["CTA_SECTION"] = generateCtaSection(dog, shelter);

    // Last updated
    placeholders["LAST_UPDATED"] = formatDate(std::chrono::system_clock::now());

    return applyPlaceholders(template_content, placeholders);
}

// ============================================================================
// URGENT ROUNDUP GENERATION
// ============================================================================

BlogPost MarkdownGenerator::generateUrgentRoundup(
    const std::vector<wtl::core::models::Dog>& dogs,
    const std::chrono::system_clock::time_point& date
) {
    BlogPost post;

    // Generate date-based title
    std::string date_str = formatDate(date, "%B %d, %Y");
    post.title = "Urgent Dogs Needing Help Today - " + date_str;
    post.slug = BlogPost::generateSlug("urgent-dogs-" + formatDate(date, "%Y-%m-%d"));

    // Generate content
    post.content = generateUrgentRoundupContent(dogs, date);

    // Generate excerpt
    std::string excerpt = std::to_string(dogs.size()) + " dogs need immediate help today. "
        "These pups are running out of time and desperately need rescue, foster, or adoption.";
    post.excerpt = excerpt;

    // Classification
    post.category = BlogCategory::URGENT;
    post.tags = {"urgent", "rescue", "euthanasia-list", "critical", "help-needed"};

    // Use first dog's photo as featured
    if (!dogs.empty() && !dogs[0].photo_urls.empty()) {
        post.featured_image = dogs[0].photo_urls[0];
    }

    // Status
    post.status = PostStatus::DRAFT;

    // SEO
    auto seo = generateUrgentRoundupSeo(static_cast<int>(dogs.size()), date);
    post.meta_description = seo.description;
    post.og_title = seo.og_title;
    post.og_description = seo.og_description;

    // Author
    post.author_name = config_.default_author;
    post.is_auto_generated = true;

    // Timestamps
    post.created_at = std::chrono::system_clock::now();
    post.updated_at = post.created_at;

    return post;
}

std::string MarkdownGenerator::generateUrgentRoundupContent(
    const std::vector<wtl::core::models::Dog>& dogs,
    const std::chrono::system_clock::time_point& date
) {
    std::string template_content;
    try {
        template_content = loadTemplate("urgent_roundup.md.template");
    } catch (...) {
        // Inline fallback template
        template_content = R"(# Urgent Dogs Needing Help - {{DATE}}

**{{DOG_COUNT}} dogs need your help TODAY.**

These dogs are in critical situations at shelters with limited space. Without rescue, foster, or adoption, they may not have much time. Please share widely!

---

{{URGENT_DOG_LIST}}

---

## How You Can Help

1. **Adopt** - Give one of these dogs a forever home
2. **Foster** - Provide temporary care while we find them a family
3. **Share** - Spread the word on social media
4. **Donate** - Help cover transport and medical costs
5. **Contact a Rescue** - Many rescues pull from kill shelters

Every share could save a life. Please help us get these dogs to safety!

---

*Updated: {{LAST_UPDATED}}*
)";
    }

    std::map<std::string, std::string> placeholders;

    placeholders["DATE"] = formatDate(date, "%B %d, %Y");
    placeholders["DOG_COUNT"] = std::to_string(dogs.size());

    // Generate list of urgent dogs
    std::ostringstream dog_list;
    int index = 1;
    for (const auto& dog : dogs) {
        dog_list << generateUrgentDogEntry(dog, index++) << "\n\n";
    }
    placeholders["URGENT_DOG_LIST"] = dog_list.str();

    placeholders["LAST_UPDATED"] = formatDate(std::chrono::system_clock::now(), "%Y-%m-%d %H:%M UTC");

    return applyPlaceholders(template_content, placeholders);
}

// ============================================================================
// SUCCESS STORY GENERATION
// ============================================================================

BlogPost MarkdownGenerator::generateSuccessStory(
    const wtl::core::models::Dog& dog,
    const wtl::core::models::FosterPlacement& adoption,
    const std::string& adopter_story,
    const std::vector<std::string>& after_photos
) {
    BlogPost post;

    // Generate title
    post.title = dog.name + "'s Happy Ending: A Success Story";
    post.slug = BlogPost::generateSlug(dog.name + "-success-story-" + dog.id.substr(0, 8));

    // Generate content
    post.content = generateSuccessStoryContent(dog, adoption, adopter_story, after_photos);

    // Generate excerpt
    std::string excerpt = dog.name + " waited " + formatWaitTime(dog.intake_date) +
        " for a family, and finally found their forever home! Read their heartwarming story.";
    post.excerpt = truncateAtWord(excerpt, config_.max_excerpt_length);

    // Classification
    post.category = BlogCategory::SUCCESS_STORY;
    post.tags = {"success-story", "adoption", "happy-ending", dog.breed_primary};

    // Media
    if (!after_photos.empty()) {
        post.featured_image = after_photos[0];
        post.gallery_images = after_photos;
    } else if (!dog.photo_urls.empty()) {
        post.featured_image = dog.photo_urls[0];
    }

    // Relationships
    post.dog_id = dog.id;
    post.adoption_id = adoption.id;

    // Status
    post.status = PostStatus::DRAFT;

    // SEO
    auto seo = generateSuccessStorySeo(dog);
    post.meta_description = seo.description;
    post.og_title = seo.og_title;
    post.og_description = seo.og_description;

    // Author
    post.author_name = config_.default_author;
    post.is_auto_generated = true;

    // Timestamps
    post.created_at = std::chrono::system_clock::now();
    post.updated_at = post.created_at;

    return post;
}

std::string MarkdownGenerator::generateSuccessStoryContent(
    const wtl::core::models::Dog& dog,
    const wtl::core::models::FosterPlacement& adoption,
    const std::string& adopter_story,
    const std::vector<std::string>& after_photos
) {
    std::string template_content;
    try {
        template_content = loadTemplate("success_story.md.template");
    } catch (...) {
        // Inline fallback template
        template_content = R"(# {{DOG_NAME}}'s Happy Ending

{{FEATURED_IMAGE}}

## The Journey

{{DOG_NAME}} came to us on {{INTAKE_DATE}} and waited **{{WAIT_TIME}}** for their perfect match.

{{DOG_DESCRIPTION}}

## Finding Home

{{ADOPTION_STORY}}

{{AFTER_PHOTOS}}

## A Message of Hope

{{DOG_NAME}}'s story reminds us that every dog deserves a chance. There are thousands more like {{DOG_NAME}} still waiting at shelters across the country.

**Will you be the happy ending for another dog?**

[View Dogs Waiting for Adoption]({{SITE_URL}}/dogs)

---

*Thank you for sharing in {{DOG_NAME}}'s joy! Every adoption success story inspires others to adopt.*
)";
    }

    std::map<std::string, std::string> placeholders;

    placeholders["DOG_NAME"] = dog.name;

    // Featured image - prefer after photo
    if (!after_photos.empty()) {
        placeholders["FEATURED_IMAGE"] = "![" + dog.name + " in their new home](" + after_photos[0] + ")";
    } else if (!dog.photo_urls.empty()) {
        placeholders["FEATURED_IMAGE"] = "![" + dog.name + "](" + dog.photo_urls[0] + ")";
    } else {
        placeholders["FEATURED_IMAGE"] = "";
    }

    placeholders["INTAKE_DATE"] = formatDate(dog.intake_date);
    placeholders["WAIT_TIME"] = formatWaitTime(dog.intake_date);
    placeholders["DOG_DESCRIPTION"] = dog.description.empty() ?
        dog.name + " was looking for love." : dog.description;

    // Adoption story
    if (!adopter_story.empty()) {
        placeholders["ADOPTION_STORY"] = "> \"" + adopter_story + "\"";
    } else {
        std::string outcome_text;
        if (adoption.outcome == "adopted_by_foster") {
            outcome_text = "After being fostered, " + dog.name + "'s foster family fell in love "
                "and decided to make it official. Sometimes the best matches are the ones you don't expect!";
        } else {
            outcome_text = dog.name + " found their forever family and is now living the happy life "
                "they always deserved. The transition has been wonderful!";
        }
        placeholders["ADOPTION_STORY"] = outcome_text;
    }

    // After photos gallery
    if (after_photos.size() > 1) {
        placeholders["AFTER_PHOTOS"] = "## Life at Home\n\n" + generatePhotoGallery(after_photos);
    } else {
        placeholders["AFTER_PHOTOS"] = "";
    }

    placeholders["SITE_URL"] = config_.site_url;

    return applyPlaceholders(template_content, placeholders);
}

// ============================================================================
// EDUCATIONAL CONTENT GENERATION
// ============================================================================

BlogPost MarkdownGenerator::generateEducationalPost(
    const std::string& topic,
    const Json::Value& custom_data
) {
    BlogPost post;

    // Map topic to title and content
    std::map<std::string, std::string> topic_titles = {
        {"puppy-care", "Complete Guide to Puppy Care"},
        {"adult-dog-care", "Caring for Your Adult Dog"},
        {"senior-dog-care", "Caring for Senior Dogs: A Complete Guide"},
        {"health-basics", "Dog Health Basics Every Owner Should Know"},
        {"training-101", "Dog Training 101: Essential Commands"},
        {"nutrition-guide", "Dog Nutrition: What to Feed Your Pup"},
        {"first-time-owner", "First-Time Dog Owner's Guide"},
        {"adoption-prep", "Preparing Your Home for a New Dog"}
    };

    auto title_it = topic_titles.find(topic);
    post.title = (title_it != topic_titles.end()) ?
        title_it->second : "Dog Care Guide: " + topic;

    post.slug = BlogPost::generateSlug(post.title);

    // Generate content
    post.content = generateEducationalContent(topic, custom_data);

    // Generate excerpt
    post.excerpt = generateExcerpt(post.content, config_.max_excerpt_length);

    // Classification
    post.category = BlogCategory::EDUCATIONAL;
    post.tags = {"educational", "dog-care", topic};

    // Status
    post.status = PostStatus::DRAFT;

    // SEO
    post.meta_description = truncateAtWord(stripMarkdown(post.content), config_.max_meta_description_length);

    // Author
    post.author_name = config_.default_author;
    post.is_auto_generated = true;

    // Timestamps
    post.created_at = std::chrono::system_clock::now();
    post.updated_at = post.created_at;

    return post;
}

std::string MarkdownGenerator::generateEducationalContent(
    const std::string& topic,
    const Json::Value& custom_data
) {
    // Try to load topic-specific template
    std::string template_name = "educational/" + topic + ".md.template";
    std::string template_content;

    try {
        template_content = loadTemplate(template_name);
    } catch (...) {
        // Generic educational template
        template_content = R"(# {{TITLE}}

{{INTRODUCTION}}

## Key Points

{{KEY_POINTS}}

## Getting Started

{{GETTING_STARTED}}

## Tips & Best Practices

{{TIPS}}

## Conclusion

{{CONCLUSION}}

---

*Have questions? Our community is here to help you on your dog parenting journey!*
)";
    }

    std::map<std::string, std::string> placeholders;

    // Use custom data if provided
    if (custom_data.isMember("title")) {
        placeholders["TITLE"] = custom_data["title"].asString();
    } else {
        placeholders["TITLE"] = "Dog Care Guide";
    }

    if (custom_data.isMember("introduction")) {
        placeholders["INTRODUCTION"] = custom_data["introduction"].asString();
    } else {
        placeholders["INTRODUCTION"] = "Taking care of a dog is a rewarding experience that "
            "requires knowledge and commitment. This guide will help you provide the best care for your canine companion.";
    }

    if (custom_data.isMember("key_points") && custom_data["key_points"].isArray()) {
        std::ostringstream points;
        for (const auto& point : custom_data["key_points"]) {
            points << "- " << point.asString() << "\n";
        }
        placeholders["KEY_POINTS"] = points.str();
    } else {
        placeholders["KEY_POINTS"] = "- Provide proper nutrition\n"
            "- Ensure regular exercise\n"
            "- Schedule veterinary checkups\n"
            "- Give plenty of love and attention\n";
    }

    if (custom_data.isMember("getting_started")) {
        placeholders["GETTING_STARTED"] = custom_data["getting_started"].asString();
    } else {
        placeholders["GETTING_STARTED"] = "Start by understanding your dog's specific needs based "
            "on their breed, age, and health condition. Every dog is unique!";
    }

    if (custom_data.isMember("tips")) {
        placeholders["TIPS"] = custom_data["tips"].asString();
    } else {
        placeholders["TIPS"] = "1. Establish a routine\n"
            "2. Be patient and consistent\n"
            "3. Use positive reinforcement\n"
            "4. Monitor your dog's health\n"
            "5. Build a strong bond through quality time\n";
    }

    if (custom_data.isMember("conclusion")) {
        placeholders["CONCLUSION"] = custom_data["conclusion"].asString();
    } else {
        placeholders["CONCLUSION"] = "Remember, every dog deserves love, care, and patience. "
            "With the right knowledge and dedication, you can provide a wonderful life for your furry friend.";
    }

    return applyPlaceholders(template_content, placeholders);
}

// ============================================================================
// SEO OPTIMIZATION
// ============================================================================

SeoMetadata MarkdownGenerator::generateDogFeatureSeo(
    const wtl::core::models::Dog& dog,
    const std::optional<wtl::core::models::Shelter>& shelter
) {
    SeoMetadata seo;

    // Title (max 60 chars)
    std::string title = "Adopt " + dog.name + " - " + dog.breed_primary + " for Adoption";
    seo.title = truncateAtWord(title, 60);

    // Description (max 155 chars)
    std::string desc = dog.name + " is a " + dog.age_category + " " + dog.breed_primary +
        " waiting for adoption. " + formatWaitTime(dog.intake_date) + " waiting.";
    seo.description = truncateAtWord(desc, 155);

    // Open Graph
    seo.og_title = seo.title;
    seo.og_description = seo.description;
    if (!dog.photo_urls.empty()) {
        seo.og_image = dog.photo_urls[0];
    }

    // Canonical URL
    seo.canonical_url = config_.site_url + "/blog/" + BlogPost::generateSlug(
        "meet-" + dog.name + "-" + dog.id.substr(0, 8));

    // Keywords
    seo.keywords = generateDogKeywords(dog);

    return seo;
}

SeoMetadata MarkdownGenerator::generateUrgentRoundupSeo(
    int dog_count,
    const std::chrono::system_clock::time_point& date
) {
    SeoMetadata seo;

    std::string date_str = formatDate(date, "%B %d, %Y");

    seo.title = std::to_string(dog_count) + " Dogs Need Help Today - " + date_str;
    seo.description = "URGENT: " + std::to_string(dog_count) +
        " dogs are at risk and need immediate adoption, fostering, or rescue. See how you can help save lives today.";

    seo.og_title = "URGENT: " + std::to_string(dog_count) + " Dogs Need Your Help Today";
    seo.og_description = seo.description;

    seo.canonical_url = config_.site_url + "/blog/urgent-dogs-" + formatDate(date, "%Y-%m-%d");

    seo.keywords = {"urgent adoption", "rescue dogs", "dogs need help", "euthanasia list", "shelter dogs"};

    return seo;
}

SeoMetadata MarkdownGenerator::generateSuccessStorySeo(const wtl::core::models::Dog& dog) {
    SeoMetadata seo;

    seo.title = dog.name + "'s Adoption Success Story | " + config_.site_name;
    seo.description = "Read " + dog.name + "'s heartwarming adoption success story. "
        "From shelter to forever home - an inspiring tale of hope.";

    seo.og_title = dog.name + " Found a Forever Home!";
    seo.og_description = seo.description;
    if (!dog.photo_urls.empty()) {
        seo.og_image = dog.photo_urls[0];
    }

    seo.keywords = {"adoption success", "shelter dog", dog.breed_primary, "happy ending", "dog adoption"};

    return seo;
}

std::vector<std::string> MarkdownGenerator::generateDogKeywords(const wtl::core::models::Dog& dog) {
    std::vector<std::string> keywords;

    keywords.push_back(dog.breed_primary);
    keywords.push_back(dog.age_category + " dog");
    keywords.push_back(dog.size + " dog");
    keywords.push_back("adopt " + dog.breed_primary);
    keywords.push_back(dog.gender + " dog");
    keywords.push_back("shelter dog");
    keywords.push_back("dog adoption");

    // Add tags
    for (const auto& tag : dog.tags) {
        keywords.push_back(tag);
    }

    return keywords;
}

// ============================================================================
// TEMPLATE UTILITIES
// ============================================================================

std::string MarkdownGenerator::loadTemplate(const std::string& template_name) {
    std::lock_guard<std::mutex> lock(mutex_);

    // Check cache first
    auto it = template_cache_.find(template_name);
    if (it != template_cache_.end()) {
        return it->second;
    }

    // Load from file
    std::string path = config_.template_directory + "/" + template_name;
    std::ifstream file(path);

    if (!file.is_open()) {
        throw std::runtime_error("Failed to load template: " + path);
    }

    std::ostringstream ss;
    ss << file.rdbuf();
    std::string content = ss.str();

    // Cache for future use
    template_cache_[template_name] = content;

    return content;
}

std::string MarkdownGenerator::applyPlaceholders(
    const std::string& template_content,
    const std::map<std::string, std::string>& placeholders
) {
    std::string result = template_content;

    for (const auto& [key, value] : placeholders) {
        std::string placeholder = "{{" + key + "}}";
        size_t pos = 0;
        while ((pos = result.find(placeholder, pos)) != std::string::npos) {
            result.replace(pos, placeholder.length(), value);
            pos += value.length();
        }
    }

    return result;
}

std::string MarkdownGenerator::generateExcerpt(const std::string& content, size_t max_length) {
    std::string text = stripMarkdown(content);

    // Trim whitespace
    size_t start = text.find_first_not_of(" \t\n\r");
    if (start == std::string::npos) return "";
    size_t end = text.find_last_not_of(" \t\n\r");
    text = text.substr(start, end - start + 1);

    return truncateAtWord(text, max_length);
}

std::string MarkdownGenerator::formatDate(
    const std::chrono::system_clock::time_point& tp,
    const std::string& format
) {
    std::time_t time = std::chrono::system_clock::to_time_t(tp);
    std::tm tm;

#ifdef _WIN32
    localtime_s(&tm, &time);
#else
    localtime_r(&time, &tm);
#endif

    std::ostringstream ss;
    ss << std::put_time(&tm, format.c_str());
    return ss.str();
}

std::string MarkdownGenerator::formatWaitTime(const std::chrono::system_clock::time_point& intake_date) {
    auto now = std::chrono::system_clock::now();
    auto duration = now - intake_date;

    auto days = std::chrono::duration_cast<std::chrono::hours>(duration).count() / 24;

    if (days < 1) {
        return "less than a day";
    } else if (days == 1) {
        return "1 day";
    } else if (days < 7) {
        return std::to_string(days) + " days";
    } else if (days < 30) {
        int weeks = static_cast<int>(days / 7);
        return weeks == 1 ? "1 week" : std::to_string(weeks) + " weeks";
    } else if (days < 365) {
        int months = static_cast<int>(days / 30);
        return months == 1 ? "1 month" : std::to_string(months) + " months";
    } else {
        int years = static_cast<int>(days / 365);
        int remaining_months = static_cast<int>((days % 365) / 30);
        if (remaining_months > 0) {
            return std::to_string(years) + " year" + (years > 1 ? "s" : "") +
                " and " + std::to_string(remaining_months) + " month" + (remaining_months > 1 ? "s" : "");
        }
        return years == 1 ? "1 year" : std::to_string(years) + " years";
    }
}

std::string MarkdownGenerator::formatCountdown(const std::chrono::system_clock::time_point& euthanasia_date) {
    auto now = std::chrono::system_clock::now();
    auto duration = euthanasia_date - now;

    if (duration.count() <= 0) {
        return "TIME'S UP";
    }

    auto hours = std::chrono::duration_cast<std::chrono::hours>(duration).count();
    auto days = hours / 24;
    hours = hours % 24;

    if (days > 0) {
        return std::to_string(days) + " day" + (days > 1 ? "s" : "") +
            ", " + std::to_string(hours) + " hour" + (hours > 1 ? "s" : "");
    } else {
        return std::to_string(hours) + " hour" + (hours > 1 ? "s" : "");
    }
}

// ============================================================================
// PRIVATE HELPERS
// ============================================================================

std::string MarkdownGenerator::generateDogFeatureTitle(const wtl::core::models::Dog& dog) {
    // Generate engaging title based on dog characteristics
    if (dog.urgency_level == "critical") {
        return "URGENT: " + dog.name + " Needs You Now!";
    } else if (dog.age_category == "senior") {
        return "Meet " + dog.name + ": A Gentle Senior Looking for Love";
    } else if (dog.age_category == "puppy") {
        return "Meet " + dog.name + ": An Adorable Pup Ready for Adventure";
    } else {
        return "Meet " + dog.name + ": A Wonderful " + dog.breed_primary + " Waiting for You";
    }
}

std::string MarkdownGenerator::generatePhotoGallery(const std::vector<std::string>& photos) {
    if (photos.empty()) return "";

    std::ostringstream gallery;
    for (size_t i = 0; i < photos.size(); ++i) {
        gallery << "![Photo " << (i + 1) << "](" << photos[i] << ")\n\n";
    }
    return gallery.str();
}

std::string MarkdownGenerator::generateDogAttributes(const wtl::core::models::Dog& dog) {
    std::ostringstream attrs;

    attrs << "| Attribute | Value |\n";
    attrs << "|-----------|-------|\n";
    attrs << "| **Breed** | " << dog.breed_primary;
    if (dog.breed_secondary) {
        attrs << " / " << *dog.breed_secondary;
    }
    attrs << " |\n";

    attrs << "| **Age** | " << dog.age_months / 12 << " years, " << dog.age_months % 12 << " months |\n";
    attrs << "| **Size** | " << dog.size << " |\n";
    attrs << "| **Gender** | " << dog.gender << " |\n";

    if (dog.weight_lbs) {
        attrs << "| **Weight** | " << *dog.weight_lbs << " lbs |\n";
    }

    attrs << "| **Color** | " << dog.color_primary;
    if (dog.color_secondary) {
        attrs << " / " << *dog.color_secondary;
    }
    attrs << " |\n";

    return attrs.str();
}

std::string MarkdownGenerator::generatePersonalitySection(const wtl::core::models::Dog& dog) {
    std::ostringstream section;

    if (dog.tags.empty()) {
        return dog.name + " has a wonderful personality and would make a great companion!";
    }

    section << dog.name << " is:\n\n";
    for (const auto& tag : dog.tags) {
        // Convert tag to readable format
        std::string readable = tag;
        std::replace(readable.begin(), readable.end(), '_', ' ');
        std::replace(readable.begin(), readable.end(), '-', ' ');

        section << "- " << readable << "\n";
    }

    return section.str();
}

std::string MarkdownGenerator::generateCtaSection(
    const wtl::core::models::Dog& dog,
    const std::optional<wtl::core::models::Shelter>& shelter
) {
    std::ostringstream cta;

    cta << "## Ready to Meet " << dog.name << "?\n\n";

    if (shelter) {
        cta << "**" << shelter->name << "**\n\n";
        if (shelter->phone.has_value() && !shelter->phone->empty()) {
            cta << "- Phone: " << *shelter->phone << "\n";
        }
        if (shelter->email.has_value() && !shelter->email->empty()) {
            cta << "- Email: " << *shelter->email << "\n";
        }
        if (!shelter->city.empty() && !shelter->state_code.empty()) {
            cta << "- Location: " << shelter->city << ", " << shelter->state_code << "\n";
        }
    }

    cta << "\n[Apply to Adopt " << dog.name << "](" << config_.site_url << "/dogs/" << dog.id << "/apply)\n\n";
    cta << "[View All Available Dogs](" << config_.site_url << "/dogs)\n";

    return cta.str();
}

std::string MarkdownGenerator::generateUrgentDogEntry(
    const wtl::core::models::Dog& dog,
    int index
) {
    std::ostringstream entry;

    entry << "### " << index << ". " << dog.name;

    if (dog.urgency_level == "critical") {
        entry << " - **CRITICAL**";
    }
    entry << "\n\n";

    if (!dog.photo_urls.empty()) {
        entry << "![" << dog.name << "](" << dog.photo_urls[0] << ")\n\n";
    }

    entry << "- **Breed:** " << dog.breed_primary << "\n";
    entry << "- **Age:** " << dog.age_category << "\n";
    entry << "- **Size:** " << dog.size << "\n";

    if (dog.euthanasia_date) {
        entry << "- **Time Remaining:** " << formatCountdown(*dog.euthanasia_date) << "\n";
    }

    entry << "\n" << (dog.description.empty() ? dog.name + " needs help!" : dog.description.substr(0, 200));
    if (dog.description.length() > 200) {
        entry << "...";
    }
    entry << "\n\n";

    entry << "[Learn More About " << dog.name << "](" << config_.site_url << "/dogs/" << dog.id << ")";

    return entry.str();
}

std::string MarkdownGenerator::truncateAtWord(const std::string& text, size_t max_length) {
    if (text.length() <= max_length) {
        return text;
    }

    std::string result = text.substr(0, max_length);

    // Find last space
    size_t last_space = result.rfind(' ');
    if (last_space != std::string::npos && last_space > max_length / 2) {
        result = result.substr(0, last_space);
    }

    // Add ellipsis
    result += "...";

    return result;
}

std::string MarkdownGenerator::stripMarkdown(const std::string& markdown) {
    std::string text = markdown;

    // Remove headers
    std::regex header_regex("^#+\\s+", std::regex::multiline);
    text = std::regex_replace(text, header_regex, "");

    // Remove links but keep text
    std::regex link_regex("\\[([^\\]]+)\\]\\([^)]+\\)");
    text = std::regex_replace(text, link_regex, "$1");

    // Remove images
    std::regex image_regex("!\\[([^\\]]*)\\]\\([^)]+\\)");
    text = std::regex_replace(text, image_regex, "");

    // Remove bold/italic
    std::regex bold_regex("\\*\\*([^*]+)\\*\\*");
    text = std::regex_replace(text, bold_regex, "$1");
    std::regex italic_regex("\\*([^*]+)\\*");
    text = std::regex_replace(text, italic_regex, "$1");

    // Remove code
    std::regex code_regex("`([^`]+)`");
    text = std::regex_replace(text, code_regex, "$1");

    // Collapse whitespace
    std::regex whitespace_regex("\\s+");
    text = std::regex_replace(text, whitespace_regex, " ");

    return text;
}

std::string MarkdownGenerator::escapeMarkdown(const std::string& text) {
    std::string result;
    result.reserve(text.size() * 1.2);

    for (char c : text) {
        if (c == '*' || c == '_' || c == '[' || c == ']' ||
            c == '(' || c == ')' || c == '#' || c == '`' ||
            c == '!' || c == '|' || c == '\\') {
            result += '\\';
        }
        result += c;
    }

    return result;
}

} // namespace wtl::content::blog
