-- WaitingTheLongest Dog Breeds Seed Data
-- Top 50 most common dog breeds found in shelters and rescue organizations
-- Run multiple times safely with ON CONFLICT handling

INSERT INTO dog_breeds (
    name, breed_group, height_imperial, weight_imperial, life_span, temperament,
    energy_level, exercise_needs, grooming_needs, good_with_kids, good_with_dogs,
    good_with_cats, apartment_friendly, first_time_owner_friendly, image_url, description
) VALUES
-- Mixed Breeds (Most common in shelters)
(
    'Mixed Breed',
    'Unclassified',
    'Varies',
    'Varies',
    '10-15 years',
    'Friendly, Loyal, Adaptable',
    'Medium',
    'Medium',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Mixed breed dogs from shelters make wonderful companions. Each dog has a unique personality and may combine traits from multiple breeds.'
),
(
    'Labrador Mix',
    'Sporting',
    '20-24 inches',
    '55-80 lbs',
    '10-12 years',
    'Friendly, Outgoing, Even-tempered, Loyal',
    'High',
    'High',
    'Low',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Labrador mixes are some of the most popular dogs in shelters. They are friendly, energetic, and make excellent family pets.'
),
(
    'Pit Bull Mix',
    'Terrier',
    '18-21 inches',
    '40-70 lbs',
    '12-14 years',
    'Loyal, Courageous, Affectionate, Strong-willed',
    'High',
    'High',
    'Low',
    true,
    false,
    false,
    false,
    false,
    NULL,
    'Pit Bull mixes are common in shelters and can make wonderful pets with proper training and socialization. They are often misunderstood but are loyal and loving.'
),
(
    'Shepherd Mix',
    'Herding',
    '20-26 inches',
    '50-90 lbs',
    '10-12 years',
    'Intelligent, Loyal, Protective, Alert',
    'High',
    'High',
    'Medium',
    true,
    false,
    false,
    false,
    false,
    NULL,
    'Shepherd mixes are intelligent and make excellent working dogs. They require consistent training and regular exercise.'
),
(
    'Chihuahua Mix',
    'Toy',
    '6-9 inches',
    '3-6 lbs',
    '12-15 years',
    'Loyal, Alert, Spirited, Bold',
    'Medium',
    'Low',
    'Low',
    false,
    false,
    true,
    true,
    false,
    NULL,
    'Chihuahua mixes are small but spirited dogs. They can be stubborn but are intensely loyal to their families.'
),
(
    'Hound Mix',
    'Hound',
    '18-27 inches',
    '40-70 lbs',
    '12-14 years',
    'Friendly, Even-tempered, Determined, Independent',
    'Medium',
    'Medium',
    'Low',
    true,
    true,
    false,
    false,
    true,
    NULL,
    'Hound mixes are driven by scent and hunting instincts. They are generally friendly and make good family pets.'
),
(
    'Boxer Mix',
    'Working',
    '22-25 inches',
    '55-80 lbs',
    '10-12 years',
    'Playful, Loyal, Protective, Confident',
    'High',
    'High',
    'Low',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Boxer mixes are playful and energetic with a strong protective instinct. They are excellent family companions.'
),
(
    'Terrier Mix',
    'Terrier',
    '12-18 inches',
    '20-50 lbs',
    '12-14 years',
    'Tenacious, Feisty, Spirited, Bold',
    'High',
    'High',
    'Medium',
    true,
    false,
    false,
    true,
    true,
    NULL,
    'Terrier mixes are spirited and energetic. They need regular exercise and can be stubborn but are deeply loyal.'
),
(
    'Husky Mix',
    'Working',
    '20-23 inches',
    '45-60 lbs',
    '12-14 years',
    'Friendly, Energetic, Mischievous, Pack-oriented',
    'Very High',
    'Very High',
    'High',
    true,
    true,
    false,
    false,
    false,
    NULL,
    'Husky mixes are high-energy dogs that require experienced owners. They are friendly but have a strong prey drive.'
),
(
    'Retriever Mix',
    'Sporting',
    '20-24 inches',
    '50-85 lbs',
    '10-12 years',
    'Friendly, Intelligent, Outgoing, Loyal',
    'High',
    'High',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Retriever mixes are among the most popular shelter dogs. They are intelligent, friendly, and adaptable.'
),

-- Pure Breeds (Most Common in Shelters)
(
    'Pit Bull Terrier',
    'Terrier',
    '18-21 inches',
    '30-65 lbs',
    '12-14 years',
    'Loyal, Courageous, Affectionate, Strong-willed',
    'High',
    'High',
    'Low',
    true,
    false,
    false,
    false,
    false,
    NULL,
    'Pit Bulls are powerful and loyal dogs that require experienced owners and proper training. They are often misunderstood but make devoted family pets.'
),
(
    'Chihuahua',
    'Toy',
    '6-9 inches',
    '2-6 lbs',
    '14-16 years',
    'Loyal, Alert, Spirited, Bold',
    'Medium',
    'Low',
    'Low',
    false,
    false,
    true,
    true,
    false,
    NULL,
    'Chihuahuas are the smallest dog breed but have big personalities. They are loyal and alert but can be snappy.'
),
(
    'Labrador Retriever',
    'Sporting',
    '21.5-24.5 inches',
    '55-80 lbs',
    '10-12 years',
    'Friendly, Outgoing, Even-tempered, Loyal',
    'High',
    'High',
    'Low',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'The most popular breed in America, Labs are friendly, outgoing, and make excellent family pets and service dogs.'
),
(
    'German Shepherd',
    'Herding',
    '22-26 inches',
    '50-90 lbs',
    '9-13 years',
    'Intelligent, Loyal, Protective, Alert',
    'High',
    'High',
    'High',
    true,
    true,
    false,
    false,
    false,
    NULL,
    'German Shepherds are highly intelligent and versatile working dogs. They are loyal and protective but require experienced owners.'
),
(
    'Beagle',
    'Hound',
    '13-15 inches',
    '20-30 lbs',
    '12-15 years',
    'Friendly, Curious, Determined, Merry',
    'High',
    'High',
    'Low',
    true,
    true,
    false,
    true,
    true,
    NULL,
    'Beagles are friendly and curious hounds. They follow their nose and need good fencing and a secure yard.'
),
(
    'Boxer',
    'Working',
    '21-25 inches',
    '55-80 lbs',
    '10-12 years',
    'Playful, Loyal, Protective, Confident',
    'High',
    'High',
    'Low',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Boxers are playful and energetic with a puppy-like demeanor throughout their lives. They are excellent family dogs.'
),
(
    'Dachshund',
    'Hound',
    '5-9 inches',
    '11-32 lbs',
    '12-16 years',
    'Bold, Curious, Spunky, Loyal',
    'Medium',
    'Medium',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Dachshunds have long bodies and short legs. They are bold and curious but can be stubborn and prone to back problems.'
),
(
    'Siberian Husky',
    'Working',
    '20-23.5 inches',
    '45-60 lbs',
    '12-14 years',
    'Friendly, Energetic, Mischievous, Pack-oriented',
    'Very High',
    'Very High',
    'High',
    true,
    true,
    false,
    false,
    false,
    NULL,
    'Huskies are high-energy sled dogs that require extensive exercise. They are friendly but have a strong prey drive.'
),
(
    'Poodle',
    'Non-Sporting',
    '10-24 inches',
    '4-70 lbs',
    '12-15 years',
    'Intelligent, Active, Elegant, Eager-to-please',
    'High',
    'High',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Poodles come in three sizes (Toy, Miniature, Standard). They are highly intelligent and excel in obedience training.'
),
(
    'Bulldog',
    'Non-Sporting',
    '12-16 inches',
    '40-50 lbs',
    '8-10 years',
    'Gentle, Affectionate, Dignified, Willful',
    'Low',
    'Low',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Bulldogs are gentle and affectionate but have significant health issues due to their flat faces. They prefer moderate climates.'
),
(
    'Yorkshire Terrier',
    'Toy',
    '7-8 inches',
    '7 lbs',
    '11-15 years',
    'Confident, Courageous, Affectionate, Spirited',
    'Medium',
    'Medium',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Yorkies are small dogs with big personalities. They are confident and affectionate but require regular grooming.'
),
(
    'German Shepherd Dog',
    'Herding',
    '22-26 inches',
    '50-90 lbs',
    '9-13 years',
    'Intelligent, Loyal, Protective, Alert',
    'High',
    'High',
    'High',
    true,
    true,
    false,
    false,
    false,
    NULL,
    'Highly versatile working dogs used for police, military, and service work. They are loyal and protective family companions.'
),
(
    'Golden Retriever',
    'Sporting',
    '20-24 inches',
    '55-75 lbs',
    '10-12 years',
    'Friendly, Intelligent, Devoted, Loyal',
    'High',
    'High',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Golden Retrievers are one of the most popular family dogs. They are intelligent, friendly, and excellent with children.'
),
(
    'Rottweiler',
    'Working',
    '22-27 inches',
    '80-135 lbs',
    '8-11 years',
    'Confident, Loyal, Protective, Steady',
    'Medium',
    'Medium',
    'Low',
    true,
    false,
    false,
    false,
    false,
    NULL,
    'Rottweilers are powerful and protective. They require experienced owners and proper socialization but are devoted family members.'
),
(
    'Pug',
    'Toy',
    '10-13 inches',
    '14-18 lbs',
    '12-15 years',
    'Playful, Affectionate, Charming, Mischievous',
    'Low',
    'Low',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Pugs are small, playful dogs with distinctive flat faces. They are charming but prone to respiratory and health issues.'
),
(
    'Shih Tzu',
    'Toy',
    '9-10.5 inches',
    '9-16 lbs',
    '10-18 years',
    'Affectionate, Loyal, Charming, Bold',
    'Low',
    'Medium',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Shih Tzus are affectionate companion dogs. They require regular grooming but make excellent family pets.'
),
(
    'Cocker Spaniel',
    'Sporting',
    '13.5-15.5 inches',
    '25-30 lbs',
    '12-15 years',
    'Friendly, Outgoing, Eager, Affectionate',
    'High',
    'High',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Cocker Spaniels are friendly and eager to please. They require regular exercise and grooming.'
),
(
    'Bullmastiff',
    'Working',
    '24-27 inches',
    '100-130 lbs',
    '7-9 years',
    'Calm, Protective, Loyal, Affectionate',
    'Medium',
    'Medium',
    'Low',
    true,
    true,
    true,
    false,
    false,
    NULL,
    'Bullmastiffs are large, protective dogs bred to guard estates. They are calm but need experienced owners.'
),
(
    'French Bulldog',
    'Non-Sporting',
    '11-13 inches',
    '28 lbs',
    '10-12 years',
    'Playful, Affectionate, Sociable, Adaptable',
    'Low',
    'Low',
    'Low',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'French Bulldogs are small, muscular dogs with big personalities. They are adaptable and make good apartment dogs but have respiratory issues.'
),
(
    'Maltese',
    'Toy',
    '7-9 inches',
    '7 lbs',
    '12-15 years',
    'Affectionate, Gentle, Intelligent, Responsive',
    'Low',
    'Medium',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Maltese are small, gentle companion dogs with silky white coats. They require regular grooming.'
),
(
    'Shar Pei',
    'Non-Sporting',
    '18-20 inches',
    '45-60 lbs',
    '8-12 years',
    'Affectionate, Dignified, Independent, Loyal',
    'Low',
    'Medium',
    'Medium',
    true,
    true,
    false,
    true,
    false,
    NULL,
    'Shar Peis have distinctive wrinkled coats. They are affectionate but independent and can be aloof with strangers.'
),
(
    'Doberman Pinscher',
    'Working',
    '24-28 inches',
    '60-100 lbs',
    '10-12 years',
    'Alert, Fearless, Loyal, Confident',
    'High',
    'High',
    'Low',
    true,
    true,
    false,
    false,
    false,
    NULL,
    'Dobermans are elegant, powerful dogs. They are loyal and protective but require experienced owners and socialization.'
),
(
    'Bichon Frise',
    'Non-Sporting',
    '9.5-11.5 inches',
    '12-18 lbs',
    '14-15 years',
    'Cheerful, Gentle, Playful, Affectionate',
    'Medium',
    'Medium',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Bichon Frises are cheerful, fluffy companion dogs. They require regular grooming and are excellent for allergy sufferers.'
),
(
    'Schnauzer',
    'Terrier',
    '11.5-19.5 inches',
    '11-50 lbs',
    '12-14 years',
    'Spirited, Alert, Obedient, Intelligent',
    'High',
    'High',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Schnauzers come in three sizes. They are intelligent and alert but require regular grooming.'
),
(
    'Basset Hound',
    'Hound',
    '12-15 inches',
    '40-65 lbs',
    '12-13 years',
    'Friendly, Stubborn, Calm, Even-tempered',
    'Low',
    'Medium',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Basset Hounds have long ears and short legs. They are friendly and calm but are determined scent followers.'
),
(
    'Dalmatian',
    'Non-Sporting',
    '19-24 inches',
    '45-70 lbs',
    '11-13 years',
    'Active, Outgoing, Sensitive, Loyal',
    'Very High',
    'Very High',
    'Low',
    true,
    true,
    false,
    false,
    true,
    NULL,
    'Dalmatians are famous for their spotted coats. They are active and require significant exercise.'
),
(
    'Australian Shepherd',
    'Herding',
    '18-23 inches',
    '40-65 lbs',
    '12-15 years',
    'Smart, Work-oriented, Loyal, Alert',
    'Very High',
    'Very High',
    'Medium',
    true,
    true,
    false,
    false,
    false,
    NULL,
    'Despite their name, Australian Shepherds are from the USA. They are highly intelligent herding dogs that need mental stimulation.'
),
(
    'Pomeranian',
    'Toy',
    '6-7 inches',
    '3-7 lbs',
    '12-16 years',
    'Spirited, Bold, Confident, Lively',
    'Medium',
    'Low',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Pomeranians are small dogs with bold personalities. They can be yappy but are excellent companions.'
),
(
    'Shetland Sheepdog',
    'Herding',
    '13-16 inches',
    '15-25 lbs',
    '12-13 years',
    'Intelligent, Loyal, Affectionate, Eager',
    'High',
    'High',
    'High',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Shetland Sheepdogs are small herding dogs. They are intelligent, loyal, and excellent with families.'
),
(
    'Collie',
    'Herding',
    '22-26 inches',
    '50-75 lbs',
    '14-16 years',
    'Loyal, Affectionate, Gentle, Intelligent',
    'Medium',
    'High',
    'High',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Collies are intelligent, gentle herding dogs. They are loyal family companions that excel in obedience.'
),
(
    'Saint Bernard',
    'Working',
    '25.5-27.5 inches',
    '120-200 lbs',
    '8-10 years',
    'Friendly, Gentle, Calm, Affectionate',
    'Medium',
    'Medium',
    'High',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Saint Bernards are giant, gentle dogs. They are friendly and patient but require cool climates due to their size.'
),
(
    'Akita',
    'Working',
    '24-28 inches',
    '70-130 lbs',
    '10-12 years',
    'Dignified, Alert, Loyal, Protective',
    'Medium',
    'Medium',
    'High',
    true,
    false,
    false,
    false,
    false,
    NULL,
    'Akitas are large, powerful dogs from Japan. They are loyal and protective but require experienced owners.'
),
(
    'Great Dane',
    'Working',
    '28-34 inches',
    '110-175 lbs',
    '7-10 years',
    'Friendly, Affectionate, Alert, Dependable',
    'Low',
    'Medium',
    'Low',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Great Danes are giant gentle dogs. They are friendly and good with families but have shorter lifespans.'
),
(
    'Newfoundland',
    'Working',
    '22-28 inches',
    '100-150 lbs',
    '9-10 years',
    'Gentle, Loyal, Trustworthy, Affectionate',
    'Medium',
    'High',
    'High',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Newfoundlands are giant water dogs. They are gentle and loyal but require cool environments.'
),
(
    'Papillon',
    'Toy',
    '8-10 inches',
    '5-10 lbs',
    '13-15 years',
    'Friendly, Alert, Obedient, Intelligent',
    'High',
    'Medium',
    'Medium',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Papillons are small dogs with large ears. They are highly intelligent and excel in agility and obedience.'
),
(
    'Bulldog Terrier',
    'Terrier',
    '16-18 inches',
    '50-65 lbs',
    '11-13 years',
    'Loyal, Courageous, Affectionate, Powerful',
    'High',
    'High',
    'Low',
    true,
    false,
    false,
    true,
    false,
    NULL,
    'Bull Terriers are muscular, powerful dogs. They are loyal but require strong-willed owners and proper training.'
),
(
    'Miniature Pinscher',
    'Toy',
    '10-12.5 inches',
    '8-11 lbs',
    '12-14 years',
    'Alert, Spirited, Confident, Playful',
    'Medium',
    'Medium',
    'Low',
    true,
    true,
    true,
    true,
    true,
    NULL,
    'Miniature Pinschers are small but spirited dogs. They have big personalities and are alert watchdogs.'
),
(
    'Great Pyrenees',
    'Working',
    '25-32 inches',
    '100-160 lbs',
    '10-12 years',
    'Gentle, Affectionate, Patient, Protective',
    'Low',
    'Medium',
    'High',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Great Pyrenees are giant white dogs bred to guard livestock. They are gentle and protective but independent.'
),
(
    'Chow Chow',
    'Non-Sporting',
    '17-20 inches',
    '45-70 lbs',
    '8-12 years',
    'Independent, Aloof, Loyal, Dignified',
    'Low',
    'Medium',
    'High',
    true,
    false,
    false,
    true,
    false,
    NULL,
    'Chow Chows are dignified, fluffy dogs. They are loyal to their families but can be aloof and stubborn.'
),
(
    'Weimaraner',
    'Sporting',
    '23-27 inches',
    '55-90 lbs',
    '10-12 years',
    'Affectionate, Alert, Obedient, Intelligent',
    'Very High',
    'Very High',
    'Low',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Weimaraners are elegant, gray hunting dogs. They are affectionate but require experienced owners and extensive exercise.'
),
(
    'Vizsla',
    'Sporting',
    '21-24 inches',
    '45-65 lbs',
    '12-15 years',
    'Affectionate, Alert, Obedient, Energetic',
    'Very High',
    'Very High',
    'Low',
    true,
    true,
    true,
    false,
    true,
    NULL,
    'Vizslas are affectionate, energetic hunting dogs. They bond closely with their families and need constant companionship.'
)
ON CONFLICT (name) DO NOTHING;
